[package]
name = "epkv-rpc"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
serde = "1.0.136"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
