[package]
name = "epkv-protocol"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bytes = { version = "1.1.0", features = ["serde"] }
epkv-epaxos = { path = "../epkv-epaxos" }
epkv-rocks = { path = "../epkv-rocks" }
epkv-utils = { path = "../epkv-utils" }
fnv = "1.0.7"
futures-util = { version = "0.3.21", features = ["sink"] }
scopeguard = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.34"
wgp = "0.2.0"
