[package]
name = "epkv-protocol"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
epkv-epaxos = { path = "../epkv-epaxos" }
epkv-utils = { path = "../epkv-utils" }
serde = { version = "1.0.136", features = ["derive"] }
