[package]
name = "epkv-eval"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
camino = { version = "1.0.7", features = ["serde1"] }
clap = { version = "3.1.14", features = ["derive"] }
epkv-protocol = { path = "../epkv-protocol" }
epkv-server = { path = "../epkv-server" }
epkv-utils = { path = "../epkv-utils" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"
simdutf8 = "0.1.4"
tokio = { version = "1.18.0", features = ["full"] }
