on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: '0 0 * * 0' # at midnight of each sunday
  workflow_dispatch:

name: CI

env:
  CI_RUST_TOOLCHAIN: nightly

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
          components: rustfmt, clippy
      - name: Rust check
        run: |
          cargo fmt
          cargo check
          cargo clippy
          cargo test
          cargo build --release
